services:

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - chatpdf_data:/app/app_data
    environment:
      - PROJECT_ROOT=/app
      - HF_TOKEN=${HF_TOKEN}
    healthcheck:
      test: [
        "CMD",
        "python",
        "-c",
        "import urllib.request; urllib.request.urlopen('http://localhost:8000/docs')"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
  
  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - BACKEND_URL=http://backend:8000/api

volumes:
  chatpdf_data: